version: '3.8'

services:
  erp_excel_batch_loader:
    image: python:3.11
    container_name: erp_excel_batch_loader
    volumes:
      - ./batch-loading-scripts:/app
    working_dir: /app
    command: bash -c "pip install pandas psycopg2-binary && python erp_excel_batch_loader.py"
    depends_on:
      - db
      - clickhouse
    networks:
      - my-network

  opening_balances:
    image: python:3.11
    container_name: opening_balances
    volumes:
      - ./batch-loading-scripts:/app
    working_dir: /app
    command: bash -c "pip install psycopg2-binary && python opening-balances.py"
    depends_on:
      - db
      - clickhouse
    networks:
      - my-network

  erp_to_clickhouse_etl:
    image: python:3.11
    container_name: erp_to_clickhouse_etl
    volumes:
      - ./batch-loading-scripts:/app
    working_dir: /app
    command: bash -c "pip install clickhouse-driver psycopg2-binary && python erp_to_clickhouse_etl.py"
    depends_on:
      - db
      - clickhouse
    networks:
      - my-network

  kafka-consumer:
    build: ./streaming-consumer
    container_name: kafka_consumer_container
    depends_on:
      - kafka
      - clickhouse
    networks:
      - my-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper_container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_container
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - my-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui_container
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - my-network

  debezium:
    image: debezium/connect:2.4
    container_name: debezium_container
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_REST_ADVERTISED_HOST_NAME: debezium
      CONNECT_PLUGIN_PATH: /kafka/connect,/debezium-connector-postgres
    depends_on:
      - kafka
      - db
    networks:
      - my-network

  clickhouse:
    container_name: clickhouse_container
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./click-house/star_schema.sql:/docker-entrypoint-initdb.d/star_schema.sql
      - ./click-house/data:/var/lib/clickhouse
    networks:
      - my-network

  db:
    container_name: postgres_container
    image: postgres:14.19
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --wal-level=logical
    ports:
      - "5000:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
      - ./postgres/superset_init.sql:/docker-entrypoint-initdb.d/superset_init.sql
      - ./postgres/erp_schema.sql:/docker-entrypoint-initdb.d/erp_schema.sql
    networks:
      - my-network
      
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - my-network
  jupyter:
    container_name: jupyter_container
    image: jupyter/base-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./demo_excels:/home/jovyan/demo_excels
      - ./requirements.txt:/home/jovyan/notebooks/requirements.txt
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    networks:
      - my-network
    command: bash -c "pip install -r /home/jovyan/notebooks/requirements.txt && start-notebook.sh"

  airflow:
    container_name: airflow_container
    image: apache/airflow:3.0.5
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
      AIRFLOW__API__SECRET_KEY: "your_secret_key"
      AIRFLOW__API__EXPOSE_CONFIG: "true"
      AIRFLOW__CORE__AUTH_MANAGER: "airflow.api_fastapi.auth.managers.simple.simple_auth_manager.SimpleAuthManager"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "True"
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: "UTC"
        # WEATHER_API_KEY: ${WEATHER_API_KEY}
    ports:
      - "8000:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./api_request:/opt/airflow/api_request
      - ./dbt:/opt/airflow/dbt
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    networks:
      - my-network
    command: >
      bash -c "pip install clickhouse-connect && airflow db migrate && airflow standalone"

  # dbt:
  #   image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest

  superset:
    container_name: superset_container
    image: apache/superset:3.0.0-py310
    environment:
      - SUPERSET_SECRET_KEY=my_secret_key_change_me
      - DATABASE_DIALECT=postgresql+psycopg2
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_DB=weather_data
    ports:
      - "8088:8088"
    depends_on:
      - db
    networks:
      - my-network
    command: >
      bash -c "
      pip install psycopg2-binary &&
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger"

  clickhouse:
    container_name: clickhouse_container
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./click-house/star_schema.sql:/docker-entrypoint-initdb.d/star_schema.sql
      - ./click-house/data:/var/lib/clickhouse
    networks:
      - my-network

  streaming-consumer:
    image: python:3.11
    container_name: streaming_consumer_container
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./streaming-consumer:/app
    working_dir: /app
    command: bash -c "pip install confluent-kafka clickhouse-driver && python kafka_to_clickhouse_consumer.py"
    depends_on:
      - kafka
      - clickhouse
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
